export const gameData = [
  {
    id: 1,
    name: "The Legend of Zelda: Breath of the Wild",
    genre: "Aventura",
    platform: "Nintendo Switch",
    releaseYear: 2017,
    rating: 9.7,
    difficulty: 6,
    popularity: 95,
  },
  {
    id: 2,
    name: "Super Mario Odyssey",
    genre: "Aventura",
    platform: "Nintendo Switch",
    releaseYear: 2017,
    rating: 9.5,
    difficulty: 5,
    popularity: 92,
  },
  {
    id: 3,
    name: "God of War",
    genre: "Acción",
    platform: "PlayStation",
    releaseYear: 2018,
    rating: 9.6,
    difficulty: 7,
    popularity: 89,
  },
  {
    id: 4,
    name: "Red Dead Redemption 2",
    genre: "Acción",
    platform: "PlayStation",
    releaseYear: 2018,
    rating: 9.4,
    difficulty: 6,
    popularity: 88,
  },
  {
    id: 5,
    name: "The Witcher 3: Wild Hunt",
    genre: "RPG",
    platform: "PC",
    releaseYear: 2015,
    rating: 9.8,
    difficulty: 7,
    popularity: 94,
  },
  {
    id: 6,
    name: "Minecraft",
    genre: "Simulación",
    platform: "PC",
    releaseYear: 2011,
    rating: 9.0,
    difficulty: 3,
    popularity: 98,
  },
  {
    id: 7,
    name: "Fortnite",
    genre: "Acción",
    platform: "PC",
    releaseYear: 2017,
    rating: 8.2,
    difficulty: 8,
    popularity: 96,
  },
  {
    id: 8,
    name: "Among Us",
    genre: "Estrategia",
    platform: "PC",
    releaseYear: 2018,
    rating: 7.8,
    difficulty: 4,
    popularity: 85,
  },
  {
    id: 9,
    name: "Cyberpunk 2077",
    genre: "RPG",
    platform: "PC",
    releaseYear: 2020,
    rating: 7.5,
    difficulty: 6,
    popularity: 75,
  },
  {
    id: 10,
    name: "Animal Crossing: New Horizons",
    genre: "Simulación",
    platform: "Nintendo Switch",
    releaseYear: 2020,
    rating: 8.8,
    difficulty: 2,
    popularity: 90,
  },
  {
    id: 11,
    name: "Call of Duty: Modern Warfare",
    genre: "Acción",
    platform: "Xbox",
    releaseYear: 2019,
    rating: 8.5,
    difficulty: 8,
    popularity: 87,
  },
  {
    id: 12,
    name: "FIFA 23",
    genre: "Deportes",
    platform: "PlayStation",
    releaseYear: 2022,
    rating: 8.0,
    difficulty: 6,
    popularity: 82,
  },
  {
    id: 13,
    name: "Tetris",
    genre: "Puzzle",
    platform: "Nintendo",
    releaseYear: 1984,
    rating: 9.2,
    difficulty: 7,
    popularity: 93,
  },
  {
    id: 14,
    name: "Pac-Man",
    genre: "Puzzle",
    platform: "Arcade",
    releaseYear: 1980,
    rating: 8.9,
    difficulty: 6,
    popularity: 91,
  },
  {
    id: 15,
    name: "Street Fighter II",
    genre: "Lucha",
    platform: "Arcade",
    releaseYear: 1991,
    rating: 9.1,
    difficulty: 8,
    popularity: 86,
  },
  {
    id: 16,
    name: "Super Mario Bros.",
    genre: "Aventura",
    platform: "Nintendo",
    releaseYear: 1985,
    rating: 9.3,
    difficulty: 5,
    popularity: 95,
  },
  {
    id: 17,
    name: "Grand Theft Auto V",
    genre: "Acción",
    platform: "PlayStation",
    releaseYear: 2013,
    rating: 9.0,
    difficulty: 6,
    popularity: 92,
  },
  {
    id: 18,
    name: "Overwatch",
    genre: "Acción",
    platform: "PC",
    releaseYear: 2016,
    rating: 8.7,
    difficulty: 7,
    popularity: 84,
  },
  {
    id: 19,
    name: "Portal 2",
    genre: "Puzzle",
    platform: "PC",
    releaseYear: 2011,
    rating: 9.5,
    difficulty: 6,
    popularity: 88,
  },
  {
    id: 20,
    name: "Halo 3",
    genre: "Acción",
    platform: "Xbox",
    releaseYear: 2007,
    rating: 9.2,
    difficulty: 7,
    popularity: 89,
  },
  {
    id: 21,
    name: "World of Warcraft",
    genre: "RPG",
    platform: "PC",
    releaseYear: 2004,
    rating: 9.1,
    difficulty: 8,
    popularity: 85,
  },
  {
    id: 22,
    name: "Counter-Strike: Global Offensive",
    genre: "Acción",
    platform: "PC",
    releaseYear: 2012,
    rating: 8.8,
    difficulty: 9,
    popularity: 87,
  },
  {
    id: 23,
    name: "League of Legends",
    genre: "Estrategia",
    platform: "PC",
    releaseYear: 2009,
    rating: 8.6,
    difficulty: 9,
    popularity: 91,
  },
  {
    id: 24,
    name: "Rocket League",
    genre: "Deportes",
    platform: "PlayStation",
    releaseYear: 2015,
    rating: 8.4,
    difficulty: 7,
    popularity: 83,
  },
  {
    id: 25,
    name: "Fall Guys",
    genre: "Acción",
    platform: "PlayStation",
    releaseYear: 2020,
    rating: 7.9,
    difficulty: 5,
    popularity: 78,
  },
  {
    id: 26,
    name: "Valorant",
    genre: "Acción",
    platform: "PC",
    releaseYear: 2020,
    rating: 8.3,
    difficulty: 8,
    popularity: 86,
  },
  {
    id: 27,
    name: "Apex Legends",
    genre: "Acción",
    platform: "Xbox",
    releaseYear: 2019,
    rating: 8.5,
    difficulty: 8,
    popularity: 85,
  },
  {
    id: 28,
    name: "Mario Kart 8 Deluxe",
    genre: "Carreras",
    platform: "Nintendo Switch",
    releaseYear: 2017,
    rating: 9.0,
    difficulty: 4,
    popularity: 90,
  },
  {
    id: 29,
    name: "Elden Ring",
    genre: "RPG",
    platform: "PlayStation",
    releaseYear: 2022,
    rating: 9.6,
    difficulty: 9,
    popularity: 93,
  },
  {
    id: 30,
    name: "Genshin Impact",
    genre: "RPG",
    platform: "PlayStation",
    releaseYear: 2020,
    rating: 8.7,
    difficulty: 6,
    popularity: 89,
  },
]
